image: alpine:3.8

variables:
  NODE_ENV: 'production'

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk --update add python py-pip nodejs yarn
    - pip install awscli
    - yarn install --production=false
  script:
    - yarn build
    - aws s3 cp build s3://guarnier/gitlab-ci --recursive