image: node:8.12.0-alpine

services:
  - mesosphere/aws-cli

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  NODE_ENV: 'production'

stages:
  - deploy

deploy:
  connect: mesosphere__aws-cli
  stage: deploy
  before_script:
    - yarn install --production=false
  script:
    - yarn build
    - ./aws.sh s3 cp ../build s3://guarnier/gitlab-ci --recursive