image: mesosphere/aws-cli:latest

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  NODE_ENV: 'production'

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk add nodejs=8.12.0-r0
    - apk add yarn
    - yarn install --production=false
  script:
    - yarn build
    - aws s3 cp build s3://guarnier/gitlab-ci --recursive