image: node:8.12.0

cache:
  paths:
    - node_modules/
    - .yarn

variables:
  NODE_ENV: 'production'

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script: yarn install --production=false

build:
  stage: build
  script: yarn build

deploy:
  stage: deploy
  script: aws s3 cp build s3://guarnier/gitlab-ci --recursive