language: node_js
node_js:
  "8.12.0"

before_install:
  - sudo apt-get install -y python python-pip
  - sudo pip install awscli

install:
  - yarn install --production=false

script:
  - yarn build
  - aws s3 cp build s3://guarnier/travis-ci --recursive