version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - node-modules-

      - restore_cache:
          key: awscli

      - run:
          name: Install pip
          command: sudo apt-get install -y python-pip

      - run:
          name: Install AWS cli in python virtual environment
          command: pip install awscli

      - run:
          name: Install application
          command: yarn install --production=false

      - run:
          name: Build application
          command: yarn build

      - run:
          name: Publish to AWS S3
          command: aws s3 cp build s3://guarnier/circle-ci --recursive

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}