# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-modules-

      - restore_cache:
          key: awscli

      - run:
          name: Install python
          command: sudo apt-get install -y python3 python3-pip

      - run:
          name: Install AWS cli
          command: |
            sudo python3 -m venv venv
            . venv/bin/activate
            pip install awscli

      - run: yarn install --production=false

      - run: yarn build

      - run: aws s3 cp build s3://guarnier/circle-ci --recursive

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - save_cache:
          key: awscli
          paths:
            - "venv"